version: '3.2'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: FTB
      FTB_SERVER_MOD: https://www.feed-the-beast.com/projects/ftb-presents-skyfactory-3/files/2481284
    ports:
      - 25565:25565
    volumes:
      - mc-ftb:/data

volumes:
  mc-ftb: